#include<bits/stdc++.h>
using namespace std;       


class Employee{

    // by default all these members are private
    // private : can't be accessed outside the class 
    // public: can be accessed outside the class 
    // protected: 

private: 
    string Name;
    string Company;
    int Age;

public:

    void setName(string name){

        Name = name;

    }

    string getName(){
        return Name;
    }


    //constructor-- same name as class and no return type
    /* 1. same as class name 
       2. cant have return type
       3. overloading and paraments are allowed*/

    Employee(string name, string company, int Age){
        Name= name;
        Company = company;
        this->Age = Age;
        cout<<"object "<<Name<<" is created"<<endl;
    }
 
    // DESTRUCTOR -- called when object goes out of scope Name is ~ClassName().
/**     1. No return type.
        2. Cannot be overloaded, cant have paramenters.
        3. Called automatically when an object goes out of scope. */

    ~Employee(){
        cout<<"object "<<Name<<" is deleted"<<endl;  // this by default generate by compiler when emp2 = emp1 is done 
    }

    // COPY CONSTRUCTOR  : special constructor that creates a new object as a copy of an existing object.
    /* ClassName(const ClassName& other);

    
    Employee(const Employee& other) {
    Name = other.Name;
    Age = other.Age;
    Company  = other.Company;
}  
this by default generated by compiler when emp2 = emp1 is done, its not custom copy constructor performs memberwise copy 
    */

    // CUSTOM COPY CONSTRUCTOR default code is not generated so age and company will have garbage value
       Employee(const Employee& ot) {
      this->Name = ot.Name;  
    //   other.Name = "xyz";  if we remove const in above line then we can modify the object which is being copied to the new object
}  


    void intro(){
        cout<<"Name"<<" "<<Name<<endl;
        cout<<"Company"<<" "<<Company<<endl;
        cout<<"Age"<<" "<<Age<<endl;
    }

};

int main(){
    
    // int number; 
    Employee emp1 = Employee("sam","abc",32); // constructor is called inside main; 


    // emp1.name = "sam"; 
    // emp1.company = "abc";  // cant do it because all variables are private 
    // emp1.age = 32;

    // emp1.intro();

    Employee emp2 = emp1; // here copy constructor will be called here emp 2 is initialzed using emp1 
    // simply copies the info of emp1 in emp2 but destructor will be called for all the objects.

    emp2.intro(); // gives garbage at age and company because custome copy constructor is used and there we copied set the age and name 

    

    return 0;
}